# Generated by Django 4.2.1 on 2023-05-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("rute", models.CharField(max_length=255)),
                ("users", models.CharField(max_length=40)),
                ("keys", models.CharField(max_length=20)),
                ("creat_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
